=== MoonLory/Web_5sem/lab7/xsd_schema.xsd
<?xml version="1.0"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.bsu.by"
        xmlns="http://www.bsu.by"
        elementFormDefault="qualified">

    <xs:complexType name="Appliances" abstract="true">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="powerWt" type="xs:double"/>
            <xs:element name="socket" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Bake">
        <xs:complexContent>
            <xs:extension base="Appliances">
                <xs:sequence>

                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Conditioner">
        <xs:complexContent>
            <xs:extension base="Appliances">
                <xs:sequence>

                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Dishwasher">
        <xs:complexContent>
            <xs:extension base="Appliances">
                <xs:sequence>

                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Fridge">
        <xs:complexContent>
            <xs:extension base="Appliances">
                <xs:sequence>

                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Hairdryer">
        <xs:complexContent>
            <xs:extension base="Appliances">
                <xs:sequence>

                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="VacuumCleaner">
        <xs:complexContent>
            <xs:extension base="Appliances">
                <xs:sequence>

                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="AppliancesList">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                	<xs:element name="bake" type="Bake"/>
                    <xs:element name="fridge" type="Fridge"/>
                    <xs:element name="conditioner" type="Conditioner"/>
                    <xs:element name="dishwasher" type="Dishwasher"/>
                    <xs:element name="hairdryer" type="Hairdryer"/>
                    <xs:element name="vacuumcleaner" type="VacuumCleaner"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== MoonLory/Web_5sem/lab7/appliances.xml
<?xml version="1.0" encoding="UTF-8"?>
<AppliancesList
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.bsu.by"
        xsi:schemaLocation="http://www.bsu.by xsd_schema.xsd">

    <bake>
        <name>Bake</name>
        <powerWt>10.8</powerWt>
        <socket>false</socket>
  </bake>

    <fridge>
        <name>Fridge</name>
        <powerWt>20.0</powerWt>
        <socket>false</socket>
    </fridge>

    <conditioner>
        <name>Dishwasher</name>
        <powerWt>5.6</powerWt>
        <socket>false</socket>
    </conditioner>

    <dishwasher>
        <name>Hairdryer</name>
        <powerWt>1.0</powerWt>
        <socket>false</socket>
   </dishwasher>

    <hairdryer>
        <name>Conditioner</name>
        <powerWt>1.0</powerWt>
        <socket>false</socket>
   </hairdryer>

    <vacuumcleaner>
        <name>VacuumCleaner</name>
        <powerWt>64.0</powerWt>
        <socket>false</socket>
   </vacuumcleaner>

</AppliancesList>
